"""create_material_generation_tables

Revision ID: 2efbe8e45c7f
Revises: 0001_create_manual_rag_documents
Create Date: 2026-06-12 10:21:52.882082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_create_material_tables"
down_revision: str | None = "0001_create_manual_rag_documents"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_experiments",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("experiment_hash", sa.String(length=64), nullable=False),
        sa.Column("machine_type", sa.String(length=100), nullable=False),
        sa.Column("inputs_json", sa.JSON(), nullable=False),
        sa.Column("normalized_inputs_json", sa.JSON(), nullable=False),
        sa.Column("process_conditions_json", sa.JSON(), nullable=True),
        sa.Column("classification", sa.String(length=50), nullable=False),
        sa.Column("result_type", sa.String(length=50), nullable=False),
        sa.Column("recipe_name", sa.String(length=255), nullable=True),
        sa.Column("material_id", sa.String(length=100), nullable=True),
        sa.Column("output_items_json", sa.JSON(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("similar_experiments_json", sa.JSON(), nullable=True),
        sa.Column("llm_used", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("llm_prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("llm_confidence", sa.Float(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_hash"),
    )
    op.create_table(
        "generated_material_discoveries",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("material_id", sa.String(length=100), nullable=False),
        sa.Column("player_id", sa.String(length=100), nullable=False),
        sa.Column("experiment_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generated_materials",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("material_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("rarity", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("properties_json", sa.JSON(), nullable=False),
        sa.Column("risks_json", sa.JSON(), nullable=True),
        sa.Column("usage_json", sa.JSON(), nullable=True),
        sa.Column("recipe_candidates_json", sa.JSON(), nullable=True),
        sa.Column("source_experiment_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "generation_status",
            sa.String(length=50),
            server_default="created",
            nullable=False,
        ),
        sa.Column(
            "visual_status",
            sa.String(length=50),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("visual_prompt", sa.Text(), nullable=True),
        sa.Column("visual_asset_key", sa.String(length=255), nullable=True),
        sa.Column("texture_asset_key", sa.String(length=255), nullable=True),
        sa.Column("thumbnail_asset_key", sa.String(length=255), nullable=True),
        sa.Column("fallback_icon", sa.String(length=255), nullable=True),
        sa.Column("visual_error", sa.Text(), nullable=True),
        sa.Column("balance_score", sa.Float(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("material_hash"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_name", sa.String(length=255), nullable=False),
        sa.Column("machine_type", sa.String(length=100), nullable=False),
        sa.Column("input_item_1", sa.String(length=100), nullable=True),
        sa.Column("input_qty_1", sa.Integer(), nullable=True),
        sa.Column("input_item_2", sa.String(length=100), nullable=True),
        sa.Column("input_qty_2", sa.Integer(), nullable=True),
        sa.Column("input_item_3", sa.String(length=100), nullable=True),
        sa.Column("input_qty_3", sa.Integer(), nullable=True),
        sa.Column("output_item_1", sa.String(length=100), nullable=True),
        sa.Column("output_qty_1", sa.Integer(), nullable=True),
        sa.Column("output_item_2", sa.String(length=100), nullable=True),
        sa.Column("output_qty_2", sa.Integer(), nullable=True),
        sa.Column("crafting_time", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipes")
    op.drop_table("generated_materials")
    op.drop_table("generated_material_discoveries")
    op.drop_table("generated_experiments")
    # ### end Alembic commands ###
